/*

#Script adapted to work with PostgreSQL 9.2.5 and UMLS2018AA by Juan M. Banda (juan@jmbanda.com)
PostgreSQL load script authored and contributed by Steve Bedrick (bedricks@ohsu.edu).
Please point each 'COPY' statement to your local '/tmp/META' installation directory, or wherever you have stored the .RRF files output by MetamorphoSys. 
This script has been tested in PostgreSQL 8.2.3 on Mac OS 10.4.10


*/
DROP TABLE MRCOLS;
CREATE TABLE MRCOLS (
	COL	varchar(20),
	DES	varchar(200),
	REF	varchar(20),
	MIN	int,
	AV	numeric(5,2),
	MAX	int,
	FIL	varchar(50),
	DTY	varchar(20),
	dummy char(1)
);
COPY MRCOLS FROM '/tmp/META/MRCOLS.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRCOLS DROP COLUMN dummy;

DROP TABLE MRCONSO;
CREATE TABLE MRCONSO (
	CUI	char(12) NOT NULL,
	LAT	char(3) NOT NULL,
	TS	char(1) NOT NULL,
	LUI	char(12) NOT NULL,
	STT	varchar(3) NOT NULL,
	SUI	char(12) NOT NULL,
	ISPREF	char(1) NOT NULL,
	AUI	varchar(9) NOT NULL,
	SAUI	varchar(50),
	SCUI	varchar(50),
	SDUI	varchar(50),
	SAB	varchar(20) NOT NULL,
	TTY	varchar(20) NOT NULL,
	CODE	varchar(100) NOT NULL,
	STR	text NOT NULL,
	SRL	int NOT NULL,
	SUPPRESS	char(1) NOT NULL,
	CVF	int,
	dummy char(1)
);
COPY MRCONSO FROM '/tmp/META/MRCONSO.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRCONSO DROP COLUMN dummy;

DROP TABLE MRCUI;
CREATE TABLE MRCUI (
	CUI1	char(12) NOT NULL,
	VER	varchar(10) NOT NULL,
	REL	varchar(4) NOT NULL,
	RELA	varchar(100),
	MAPREASON	text,
	CUI2	char(12),
	MAPIN	char(1),
	dummy char(1)
);
COPY MRCUI FROM '/tmp/META/MRCUI.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRCUI DROP COLUMN dummy;

DROP TABLE MRDEF;
CREATE TABLE MRDEF (
	CUI	char(12) NOT NULL,
	AUI	varchar(9) NOT NULL,
	ATUI	varchar(15) NOT NULL,
	SATUI	varchar(50),
	SAB	varchar(20) NOT NULL,
	DEF	text NOT NULL,
	SUPPRESS	char(1) NOT NULL,
	CVF	int,
	dummy char(1)
);
COPY MRDEF FROM '/tmp/META/MRDEF.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRDEF DROP COLUMN dummy;

DROP TABLE MRDOC;
CREATE TABLE MRDOC (
	DOCKEY	varchar(50) NOT NULL,
	VALUE	varchar(200),
	TYPE	varchar(50) NOT NULL,
	EXPL	text,
	dummy char(1)
);
COPY MRDOC FROM '/tmp/META/MRDOC.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRDOC DROP COLUMN dummy;

DROP TABLE MRFILES;
CREATE TABLE MRFILES (
	FIL	varchar(50),
	DES	varchar(200),
	FMT	text,
	CLS	int,
	RWS	int,
	BTS	bigint,
	dummy char(1)
);
COPY MRFILES FROM '/tmp/META/MRFILES.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRFILES DROP COLUMN dummy;

DROP TABLE MRHIER;
CREATE TABLE MRHIER (
	CUI	char(12) NOT NULL,
	AUI	varchar(9) NOT NULL,
	CXN	int NOT NULL,
	PAUI	varchar(9),
	SAB	varchar(20) NOT NULL,
	RELA	varchar(100),
	PTR	text,
	HCD	varchar(70),
	CVF	int,
	dummy char(1)
);
COPY MRHIER FROM '/tmp/META/MRHIER.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRHIER DROP COLUMN dummy;

DROP TABLE MRHIST;
CREATE TABLE MRHIST (
	CUI	char(12) NOT NULL,
	SOURCEUI	varchar(50) NOT NULL,
	SAB	varchar(20) NOT NULL,
	SVER	varchar(20) NOT NULL,
	CHANGETYPE	text NOT NULL,
	CHANGEKEY	text NOT NULL,
	CHANGEVAL	text NOT NULL,
	REASON	text,
	CVF	int,
	dummy char(1)
);
COPY MRHIST FROM '/tmp/META/MRHIST.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRHIST DROP COLUMN dummy;

DROP TABLE MRMAP;
CREATE TABLE MRMAP (
	MAPSETCUI	char(12),
	MAPSETSAB	varchar(20),
	MAPSUBSETID	varchar(10),
	MAPRANK	int,
	MAPID	varchar(50),
	MAPSID	varchar(50),
	FROMID	varchar(50),
	FROMSID	varchar(50),
	FROMEXPR	text,
	FROMTYPE	varchar(50),
	FROMRULE	text,
	FROMRES	text,
	REL	varchar(4),
	RELA	varchar(100),
	TOID	varchar(50),
	TOSID	varchar(50),
	TOEXPR	text,
	TOTYPE	varchar(50),
	TORULE	text,
	TORES	text,
	MAPRULE	text,
	MAPRES	text,
	MAPTYPE	varchar(50),
	MAPATN	varchar(20),
	MAPATV	text,
	CVF	int,
	dummy char(1)
);
COPY MRMAP FROM '/tmp/META/MRMAP.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRMAP DROP COLUMN dummy;

DROP TABLE MRRANK;
CREATE TABLE MRRANK (
	RANK	int NOT NULL,
	SAB	varchar(20) NOT NULL,
	TTY	varchar(20) NOT NULL,
	SUPPRESS	char(1) NOT NULL,
	dummy char(1)
);
COPY MRRANK FROM '/tmp/META/MRRANK.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRRANK DROP COLUMN dummy;

DROP TABLE MRREL;
CREATE TABLE MRREL (
	CUI1	char(12) NOT NULL,
	AUI1	varchar(9),
	STYPE1	varchar(50) NOT NULL,
	REL	varchar(4) NOT NULL,
	CUI2	char(12) NOT NULL,
	AUI2	varchar(9),
	STYPE2	varchar(50) NOT NULL,
	RELA	varchar(100),
	RUI	varchar(10) NOT NULL,
	SRUI	varchar(50),
	SAB	varchar(20) NOT NULL,
	SL	varchar(20) NOT NULL,
	RG	varchar(10),
	DIR	varchar(1),
	SUPPRESS	char(1) NOT NULL,
	CVF	int,
	dummy char(1)
);
COPY MRREL FROM '/tmp/META/MRREL.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRREL DROP COLUMN dummy;

DROP TABLE MRSAB;
CREATE TABLE MRSAB (
	VCUI	char(12),
	RCUI	char(12),
	VSAB	varchar(50) NOT NULL,
	RSAB	varchar(20) NOT NULL,
	SON	text NOT NULL,
	SF	varchar(20) NOT NULL,
	SVER	varchar(20),
	VSTART	char(10),
	VEND	char(10),
	IMETA	varchar(10) NOT NULL,
	RMETA	varchar(10),
	SLC	text,
	SCC	text,
	SRL	int NOT NULL,
	TFR	int,
	CFR	int,
	CXTY	varchar(50),
	TTYL	varchar(200),
	ATNL	text,
	LAT	char(3),
	CENC	varchar(20) NOT NULL,
	CURVER	char(1) NOT NULL,
	SABIN	char(1) NOT NULL,
	SSN	text NOT NULL,
	SCIT	text NOT NULL,
	dummy char(1)
);
COPY MRSAB FROM '/tmp/META/MRSAB.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRSAB DROP COLUMN dummy;

DROP TABLE MRSAT;
CREATE TABLE MRSAT (
	CUI	char(12) NOT NULL,
	LUI	char(12),
	SUI	char(12),
	METAUI	varchar(50),
	STYPE	varchar(50) NOT NULL,
	CODE	varchar(50),
	ATUI	varchar(15) NOT NULL,
	SATUI	varchar(50),
	ATN	varchar(80) NOT NULL,
	SAB	varchar(20) NOT NULL,
	ATV	text,
	SUPPRESS	char(1) NOT NULL,
	CVF	int,
	dummy char(1)
);
COPY MRSAT FROM '/tmp/META/MRSAT.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRSAT DROP COLUMN dummy;

DROP TABLE MRSMAP;
CREATE TABLE MRSMAP (
	MAPSETCUI	char(12),
	MAPSETSAB	varchar(20),
	MAPID	varchar(50),
	MAPSID	varchar(50),
	FROMEXPR	text,
	FROMTYPE	varchar(50),
	REL	varchar(4),
	RELA	varchar(100),
	TOEXPR	text,
	TOTYPE	varchar(50),
	CVF	int,
	dummy char(1)
);
COPY MRSMAP FROM '/tmp/META/MRSMAP.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRSMAP DROP COLUMN dummy;

DROP TABLE MRSTY;
CREATE TABLE MRSTY (
	CUI	char(12) NOT NULL,
	TUI	char(4) NOT NULL,
	STN	varchar(100) NOT NULL,
	STY	varchar(50) NOT NULL,
	ATUI	varchar(15) NOT NULL,
	CVF	int,
	dummy char(1)
);
COPY MRSTY FROM '/tmp/META/MRSTY.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRSTY DROP COLUMN dummy;

DROP TABLE MRXNS_ENG;
CREATE TABLE MRXNS_ENG (
	LAT	char(3) NOT NULL,
	NSTR	text NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXNS_ENG FROM '/tmp/META/MRXNS_ENG.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXNS_ENG DROP COLUMN dummy;

DROP TABLE MRXNW_ENG;
CREATE TABLE MRXNW_ENG (
	LAT	char(3) NOT NULL,
	NWD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXNW_ENG FROM '/tmp/META/MRXNW_ENG.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXNW_ENG DROP COLUMN dummy;

DROP TABLE MRAUI;
CREATE TABLE MRAUI (
	AUI1	varchar(9) NOT NULL,
	CUI1	char(12) NOT NULL,
	VER	varchar(10) NOT NULL,
	REL	varchar(4),
	RELA	varchar(100),
	MAPREASON	text NOT NULL,
	AUI2	varchar(9) NOT NULL,
	CUI2	char(12) NOT NULL,
	MAPIN	char(1) NOT NULL,
	dummy char(1)
);
COPY MRAUI FROM '/tmp/META/MRAUI.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRAUI DROP COLUMN dummy;

DROP TABLE MRXW_BAQ;
CREATE TABLE MRXW_BAQ (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_BAQ FROM '/tmp/META/MRXW_BAQ.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_BAQ DROP COLUMN dummy;

DROP TABLE MRXW_CZE;
CREATE TABLE MRXW_CZE (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_CZE FROM '/tmp/META/MRXW_CZE.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_CZE DROP COLUMN dummy;

DROP TABLE MRXW_DAN;
CREATE TABLE MRXW_DAN (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_DAN FROM '/tmp/META/MRXW_DAN.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_DAN DROP COLUMN dummy;

DROP TABLE MRXW_DUT;
CREATE TABLE MRXW_DUT (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_DUT FROM '/tmp/META/MRXW_DUT.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_DUT DROP COLUMN dummy;

DROP TABLE MRXW_ENG;
CREATE TABLE MRXW_ENG (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_ENG FROM '/tmp/META/MRXW_ENG.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_ENG DROP COLUMN dummy;

DROP TABLE MRXW_FIN;
CREATE TABLE MRXW_FIN (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_FIN FROM '/tmp/META/MRXW_FIN.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_FIN DROP COLUMN dummy;

DROP TABLE MRXW_FRE;
CREATE TABLE MRXW_FRE (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_FRE FROM '/tmp/META/MRXW_FRE.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_FRE DROP COLUMN dummy;

DROP TABLE MRXW_GER;
CREATE TABLE MRXW_GER (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_GER FROM '/tmp/META/MRXW_GER.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_GER DROP COLUMN dummy;

DROP TABLE MRXW_HEB;
CREATE TABLE MRXW_HEB (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_HEB FROM '/tmp/META/MRXW_HEB.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_HEB DROP COLUMN dummy;

DROP TABLE MRXW_HUN;
CREATE TABLE MRXW_HUN (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_HUN FROM '/tmp/META/MRXW_HUN.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_HUN DROP COLUMN dummy;

DROP TABLE MRXW_ITA;
CREATE TABLE MRXW_ITA (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_ITA FROM '/tmp/META/MRXW_ITA.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_ITA DROP COLUMN dummy;

DROP TABLE MRXW_JPN;
CREATE TABLE MRXW_JPN (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_JPN FROM '/tmp/META/MRXW_JPN.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_JPN DROP COLUMN dummy;

DROP TABLE MRXW_NOR;
CREATE TABLE MRXW_NOR (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_NOR FROM '/tmp/META/MRXW_NOR.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_NOR DROP COLUMN dummy;

DROP TABLE MRXW_POR;
CREATE TABLE MRXW_POR (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_POR FROM '/tmp/META/MRXW_POR.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_POR DROP COLUMN dummy;

DROP TABLE MRXW_RUS;
CREATE TABLE MRXW_RUS (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_RUS FROM '/tmp/META/MRXW_RUS.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_RUS DROP COLUMN dummy;

DROP TABLE MRXW_SPA;
CREATE TABLE MRXW_SPA (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_SPA FROM '/tmp/META/MRXW_SPA.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_SPA DROP COLUMN dummy;

DROP TABLE MRXW_SWE;
CREATE TABLE MRXW_SWE (
	LAT	char(3) NOT NULL,
	WD	varchar(100) NOT NULL,
	CUI	char(12) NOT NULL,
	LUI	char(12) NOT NULL,
	SUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MRXW_SWE FROM '/tmp/META/MRXW_SWE.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MRXW_SWE DROP COLUMN dummy;

DROP TABLE AMBIGSUI;
CREATE TABLE AMBIGSUI (
	SUI	char(12) NOT NULL,
	CUI	char(12) NOT NULL,
	dummy char(1)
);
COPY AMBIGSUI FROM '/tmp/META/AMBIGSUI.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE AMBIGSUI DROP COLUMN dummy;

DROP TABLE AMBIGLUI;
CREATE TABLE AMBIGLUI (
	LUI	char(12) NOT NULL,
	CUI	char(12) NOT NULL,
	dummy char(1)
);
COPY AMBIGLUI FROM '/tmp/META/AMBIGLUI.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE AMBIGLUI DROP COLUMN dummy;

DROP TABLE DELETEDCUI;
CREATE TABLE DELETEDCUI (
	PCUI	char(12) NOT NULL,
	PSTR	text NOT NULL,
	dummy char(1)
);
COPY DELETEDCUI FROM '/tmp/META/CHANGE/DELETEDCUI.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE DELETEDCUI DROP COLUMN dummy;

DROP TABLE DELETEDLUI;
CREATE TABLE DELETEDLUI (
	PLUI	char(12) NOT NULL,
	PSTR	text NOT NULL,
	dummy char(1)
);
COPY DELETEDLUI FROM '/tmp/META/CHANGE/DELETEDLUI.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE DELETEDLUI DROP COLUMN dummy;

DROP TABLE DELETEDSUI;
CREATE TABLE DELETEDSUI (
	PSUI	char(12) NOT NULL,
	LAT	char(3) NOT NULL,
	PSTR	text NOT NULL,
	dummy char(1)
);
COPY DELETEDSUI FROM '/tmp/META/CHANGE/DELETEDSUI.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE DELETEDSUI DROP COLUMN dummy;

DROP TABLE MERGEDCUI;
CREATE TABLE MERGEDCUI (
	PCUI	char(12) NOT NULL,
	CUI	char(12) NOT NULL,
	dummy char(1)
);
COPY MERGEDCUI FROM '/tmp/META/CHANGE/MERGEDCUI.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MERGEDCUI DROP COLUMN dummy;

DROP TABLE MERGEDLUI;
CREATE TABLE MERGEDLUI (
	PLUI	char(12),
	LUI	char(12),
	dummy char(1)
);
COPY MERGEDLUI FROM '/tmp/META/CHANGE/MERGEDLUI.RRF' WITH DELIMITER AS '|' NULL AS '';
ALTER TABLE MERGEDLUI DROP COLUMN dummy;